-- CRIAÇÃO DE TABELAS PARA POSTGRESQL

DROP TABLE IF EXISTS TBL_EQUIPMENT_USAGE_LOG;
DROP TABLE IF EXISTS TBL_EQUIPMENT;
DROP TABLE IF EXISTS TBL_SECTOR;
DROP TABLE IF EXISTS TBL_USER;

DROP SEQUENCE IF EXISTS SECTOR_SEQ;
DROP SEQUENCE IF EXISTS EQUIPMENT_SEQ;
DROP SEQUENCE IF EXISTS EQUIPMENT_LOG_SEQ;

CREATE SEQUENCE SECTOR_SEQ START 1;
CREATE SEQUENCE EQUIPMENT_SEQ START 1;
CREATE SEQUENCE EQUIPMENT_LOG_SEQ START 1;

CREATE TABLE TBL_SECTOR (
    ID INTEGER DEFAULT nextval('SECTOR_SEQ') NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    CONSUMPTION_LIMIT DECIMAL(10, 2) NOT NULL,
    CONSTRAINT PK_TBL_SECTOR PRIMARY KEY (ID)
);

CREATE TABLE TBL_EQUIPMENT (
    ID INTEGER DEFAULT nextval('EQUIPMENT_SEQ') NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    STATUS CHAR(1) DEFAULT 'I' NOT NULL,
    CONSUMPTION_PER_HOUR DOUBLE PRECISION NOT NULL,
    MAX_ACTIVE_HOURS INTEGER NOT NULL,
    LAST_ACTIVATED_AT TIMESTAMP,
    SECTOR_ID INTEGER,
    CONSTRAINT PK_TBL_EQUIPMENT PRIMARY KEY (ID),
    CONSTRAINT FK_TBL_EQUIPMENT_SECTOR FOREIGN KEY (SECTOR_ID) REFERENCES TBL_SECTOR(ID)
);

CREATE TABLE TBL_EQUIPMENT_USAGE_LOG (
    ID INTEGER DEFAULT nextval('EQUIPMENT_LOG_SEQ') NOT NULL,
    STARTED_AT TIMESTAMP NOT NULL,
    ENDED_AT TIMESTAMP NOT NULL,
    ESTIMATED_CONSUMPTION DOUBLE PRECISION,
    EQUIPMENT_ID INTEGER,
    CONSTRAINT PK_TBL_EQUIPMENT_USAGE_LOG PRIMARY KEY (ID),
    CONSTRAINT FK_TBL_EQUIPMENT_USAGE_LOG FOREIGN KEY (EQUIPMENT_ID) REFERENCES TBL_EQUIPMENT(ID)
);

-- INSERÇÃO DE DADOS

INSERT INTO TBL_SECTOR (NAME, CONSUMPTION_LIMIT) VALUES ('Setor de Produção', 1000.00);
INSERT INTO TBL_SECTOR (NAME, CONSUMPTION_LIMIT) VALUES ('Setor de Manutenção', 800.00);
INSERT INTO TBL_SECTOR (NAME, CONSUMPTION_LIMIT) VALUES ('Setor Administrativo', 500.00);
INSERT INTO TBL_SECTOR (NAME, CONSUMPTION_LIMIT) VALUES ('Setor de Pesquisa', 1200.00);

-- Equipamentos para o Setor 1
INSERT INTO TBL_EQUIPMENT (NAME, STATUS, CONSUMPTION_PER_HOUR, MAX_ACTIVE_HOURS, LAST_ACTIVATED_AT, SECTOR_ID)
VALUES ('Esteira A1', 'A', 50.00, 5, NOW() - INTERVAL '2 hours', 1);

INSERT INTO TBL_EQUIPMENT (NAME, STATUS, CONSUMPTION_PER_HOUR, MAX_ACTIVE_HOURS, LAST_ACTIVATED_AT, SECTOR_ID)
VALUES ('Prensa B2', 'I', 70.00, 4, NULL, 1);

INSERT INTO TBL_EQUIPMENT (NAME, STATUS, CONSUMPTION_PER_HOUR, MAX_ACTIVE_HOURS, LAST_ACTIVATED_AT, SECTOR_ID)
VALUES ('Motor C3', 'A', 30.00, 6, NOW() - INTERVAL '1 hour', 1);

-- Equipamentos para o Setor 2
INSERT INTO TBL_EQUIPMENT (NAME, STATUS, CONSUMPTION_PER_HOUR, MAX_ACTIVE_HOURS, LAST_ACTIVATED_AT, SECTOR_ID)
VALUES ('Ferramenta X1', 'I', 10.00, 8, NULL, 2);

INSERT INTO TBL_EQUIPMENT (NAME, STATUS, CONSUMPTION_PER_HOUR, MAX_ACTIVE_HOURS, LAST_ACTIVATED_AT, SECTOR_ID)
VALUES ('Compressor Z3', 'A', 60.00, 3, NOW() - INTERVAL '3 hours', 2);

INSERT INTO TBL_EQUIPMENT (NAME, STATUS, CONSUMPTION_PER_HOUR, MAX_ACTIVE_HOURS, LAST_ACTIVATED_AT, SECTOR_ID)
VALUES ('Maçarico Y7', 'I', 40.00, 4, NULL, 2);

-- Equipamentos para o Setor 3
INSERT INTO TBL_EQUIPMENT (NAME, STATUS, CONSUMPTION_PER_HOUR, MAX_ACTIVE_HOURS, LAST_ACTIVATED_AT, SECTOR_ID)
VALUES ('Impressora Laser', 'A', 15.00, 6, NOW() - INTERVAL '30 minutes', 3);

INSERT INTO TBL_EQUIPMENT (NAME, STATUS, CONSUMPTION_PER_HOUR, MAX_ACTIVE_HOURS, LAST_ACTIVATED_AT, SECTOR_ID)
VALUES ('Scanner 3D', 'I', 20.00, 2, NULL, 3);

INSERT INTO TBL_EQUIPMENT (NAME, STATUS, CONSUMPTION_PER_HOUR, MAX_ACTIVE_HOURS, LAST_ACTIVATED_AT, SECTOR_ID)
VALUES ('PC Design', 'A', 25.00, 8, NOW() - INTERVAL '30 minutes', 3);

-- Equipamentos para o Setor 4
INSERT INTO TBL_EQUIPMENT (NAME, STATUS, CONSUMPTION_PER_HOUR, MAX_ACTIVE_HOURS, LAST_ACTIVATED_AT, SECTOR_ID)
VALUES ('Laboratório Químico', 'I', 90.00, 5, NULL, 4);

INSERT INTO TBL_EQUIPMENT (NAME, STATUS, CONSUMPTION_PER_HOUR, MAX_ACTIVE_HOURS, LAST_ACTIVATED_AT, SECTOR_ID)
VALUES ('Microscópio Eletrônico', 'A', 45.00, 6, NOW() - INTERVAL '4 hours', 4);

INSERT INTO TBL_EQUIPMENT (NAME, STATUS, CONSUMPTION_PER_HOUR, MAX_ACTIVE_HOURS, LAST_ACTIVATED_AT, SECTOR_ID)
VALUES ('Incubadora Térmica', 'A', 35.00, 7, NOW() - INTERVAL '6 hours', 4);

-- Logs para equipamentos de ID entre 1 e 12
INSERT INTO TBL_EQUIPMENT_USAGE_LOG (STARTED_AT, ENDED_AT, ESTIMATED_CONSUMPTION, EQUIPMENT_ID) VALUES (NOW() - INTERVAL '10 hours', NOW() - INTERVAL '9.5 hours', 25.0, 1);
INSERT INTO TBL_EQUIPMENT_USAGE_LOG (STARTED_AT, ENDED_AT, ESTIMATED_CONSUMPTION, EQUIPMENT_ID) VALUES (NOW() - INTERVAL '9 hours', NOW() - INTERVAL '8.7 hours', 30.5, 2);
INSERT INTO TBL_EQUIPMENT_USAGE_LOG (STARTED_AT, ENDED_AT, ESTIMATED_CONSUMPTION, EQUIPMENT_ID) VALUES (NOW() - INTERVAL '8 hours', NOW() - INTERVAL '7.8 hours', 12.2, 3);
INSERT INTO TBL_EQUIPMENT_USAGE_LOG (STARTED_AT, ENDED_AT, ESTIMATED_CONSUMPTION, EQUIPMENT_ID) VALUES (NOW() - INTERVAL '7.5 hours', NOW() - INTERVAL '7 hours', 45.0, 4);
INSERT INTO TBL_EQUIPMENT_USAGE_LOG (STARTED_AT, ENDED_AT, ESTIMATED_CONSUMPTION, EQUIPMENT_ID) VALUES (NOW() - INTERVAL '6.2 hours', NOW() - INTERVAL '6 hours', 33.0, 5);

INSERT INTO TBL_EQUIPMENT_USAGE_LOG (STARTED_AT, ENDED_AT, ESTIMATED_CONSUMPTION, EQUIPMENT_ID) VALUES (NOW() - INTERVAL '6 hours', NOW() - INTERVAL '5.5 hours', 41.7, 6);
INSERT INTO TBL_EQUIPMENT_USAGE_LOG (STARTED_AT, ENDED_AT, ESTIMATED_CONSUMPTION, EQUIPMENT_ID) VALUES (NOW() - INTERVAL '5.5 hours', NOW() - INTERVAL '5.3 hours', 18.9, 7);
INSERT INTO TBL_EQUIPMENT_USAGE_LOG (STARTED_AT, ENDED_AT, ESTIMATED_CONSUMPTION, EQUIPMENT_ID) VALUES (NOW() - INTERVAL '5 hours', NOW() - INTERVAL '4.8 hours', 50.0, 8);
INSERT INTO TBL_EQUIPMENT_USAGE_LOG (STARTED_AT, ENDED_AT, ESTIMATED_CONSUMPTION, EQUIPMENT_ID) VALUES (NOW() - INTERVAL '4.8 hours', NOW() - INTERVAL '4.4 hours', 60.0, 9);
INSERT INTO TBL_EQUIPMENT_USAGE_LOG (STARTED_AT, ENDED_AT, ESTIMATED_CONSUMPTION, EQUIPMENT_ID) VALUES (NOW() - INTERVAL '4.5 hours', NOW() - INTERVAL '4 hours', 72.5, 10);

INSERT INTO TBL_EQUIPMENT_USAGE_LOG (STARTED_AT, ENDED_AT, ESTIMATED_CONSUMPTION, EQUIPMENT_ID) VALUES (NOW() - INTERVAL '4 hours', NOW() - INTERVAL '3.7 hours', 29.5, 11);
INSERT INTO TBL_EQUIPMENT_USAGE_LOG (STARTED_AT, ENDED_AT, ESTIMATED_CONSUMPTION, EQUIPMENT_ID) VALUES (NOW() - INTERVAL '3.5 hours', NOW() - INTERVAL '3 hours', 37.0, 12);
INSERT INTO TBL_EQUIPMENT_USAGE_LOG (STARTED_AT, ENDED_AT, ESTIMATED_CONSUMPTION, EQUIPMENT_ID) VALUES (NOW() - INTERVAL '3 hours', NOW() - INTERVAL '2.7 hours', 22.3, 1);
INSERT INTO TBL_EQUIPMENT_USAGE_LOG (STARTED_AT, ENDED_AT, ESTIMATED_CONSUMPTION, EQUIPMENT_ID) VALUES (NOW() - INTERVAL '2.7 hours', NOW() - INTERVAL '2.3 hours', 55.0, 2);
INSERT INTO TBL_EQUIPMENT_USAGE_LOG (STARTED_AT, ENDED_AT, ESTIMATED_CONSUMPTION, EQUIPMENT_ID) VALUES (NOW() - INTERVAL '2.2 hours', NOW() - INTERVAL '2 hours', 40.4, 3);

INSERT INTO TBL_EQUIPMENT_USAGE_LOG (STARTED_AT, ENDED_AT, ESTIMATED_CONSUMPTION, EQUIPMENT_ID) VALUES (NOW() - INTERVAL '2 hours', NOW() - INTERVAL '1.5 hours', 60.0, 4);
INSERT INTO TBL_EQUIPMENT_USAGE_LOG (STARTED_AT, ENDED_AT, ESTIMATED_CONSUMPTION, EQUIPMENT_ID) VALUES (NOW() - INTERVAL '1.8 hours', NOW() - INTERVAL '1.4 hours', 20.0, 5);
INSERT INTO TBL_EQUIPMENT_USAGE_LOG (STARTED_AT, ENDED_AT, ESTIMATED_CONSUMPTION, EQUIPMENT_ID) VALUES (NOW() - INTERVAL '1.3 hours', NOW() - INTERVAL '1 hour', 45.9, 6);
INSERT INTO TBL_EQUIPMENT_USAGE_LOG (STARTED_AT, ENDED_AT, ESTIMATED_CONSUMPTION, EQUIPMENT_ID) VALUES (NOW() - INTERVAL '54 minutes', NOW() - INTERVAL '36 minutes', 19.8, 7);
INSERT INTO TBL_EQUIPMENT_USAGE_LOG (STARTED_AT, ENDED_AT, ESTIMATED_CONSUMPTION, EQUIPMENT_ID) VALUES (NOW() - INTERVAL '30 minutes', NOW() - INTERVAL '6 minutes', 33.3, 8);