-- CRIAÇÃO DE TABELAS

DROP SEQUENCE SECTOR_SEQ;
DROP SEQUENCE EQUIPMENT_SEQ;
DROP SEQUENCE EQUIPMENT_LOG_SEQ;

DROP TABLE TBL_USER;
DROP TABLE TBL_SECTOR;
DROP TABLE TBL_EQUIPMENT;
DROP TABLE TBL_EQUIPMENT_USAGE_LOG;


CREATE SEQUENCE SECTOR_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE TBL_SECTOR (
    ID INTEGER DEFAULT SECTOR_SEQ.nextval NOT NULL,
    NAME VARCHAR2(100) NOT NULL,
    CONSUMPTION_LIMIT NUMBER(10, 2) NOT NULL,
    CONSTRAINT PK_TBL_SECTOR PRIMARY KEY (ID)
)

CREATE SEQUENCE EQUIPMENT_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE EQUIPMENT_LOG_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE TBL_EQUIPMENT (
    ID INTEGER DEFAULT EQUIPMENT_SEQ.NEXTVAL NOT NULL,
    name VARCHAR(100) NOT NULL,
    --I -> Inativo; A -> Ativo
    status CHAR(1) DEFAULT 'I' NOT NULL,
    consumption_per_hour DOUBLE PRECISION NOT NULL,
    max_active_hours INTEGER NOT NULL,
    last_activated_at TIMESTAMP,
    CONSTRAINT PK_TBL_EQUIPMENT PRIMARY KEY (ID),
    sector_id INTEGER REFERENCES tbl_sector(id)
);

CREATE TABLE TBL_EQUIPMENT_USAGE_LOG (
    id INTEGER DEFAULT EQUIPMENT_LOG_SEQ.NEXTVAL NOT NULL,
    started_at TIMESTAMP NOT NULL,
    ended_at TIMESTAMP NOT NULL,
    estimated_consumption DOUBLE PRECISION,
    CONSTRAINT PK_TBL_EQUIPMENT_USAGE_LOG PRIMARY KEY (ID),
    equipment_id REFERENCES tbl_equipment(id)
);


